// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWAf74yDjUwX4onjT2xWFNX9Hp-qmcLUs',
    appId: '1:160105155630:web:53ef3dbe92256d9ea8e3bf',
    messagingSenderId: '160105155630',
    projectId: 'bubble-acfaf',
    authDomain: 'bubble-acfaf.firebaseapp.com',
    storageBucket: 'bubble-acfaf.appspot.com',
    measurementId: 'G-2Q7LRC8DKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeJsX3q4K2wFI3xeBupzNnJtrw9SSDj64',
    appId: '1:160105155630:android:1b0806ebc12edf5ea8e3bf',
    messagingSenderId: '160105155630',
    projectId: 'bubble-acfaf',
    storageBucket: 'bubble-acfaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0MTeKKPvpGG6502OnFdmlo3IbBlqgljg',
    appId: '1:160105155630:ios:58d92e415c10f627a8e3bf',
    messagingSenderId: '160105155630',
    projectId: 'bubble-acfaf',
    storageBucket: 'bubble-acfaf.appspot.com',
    iosBundleId: 'com.example.mypfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0MTeKKPvpGG6502OnFdmlo3IbBlqgljg',
    appId: '1:160105155630:ios:86cedc8f701ea59ba8e3bf',
    messagingSenderId: '160105155630',
    projectId: 'bubble-acfaf',
    storageBucket: 'bubble-acfaf.appspot.com',
    iosBundleId: 'com.example.mypfe.RunnerTests',
  );
}
